# Generated by Django 4.2.4 on 2023-08-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw_2_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
    ]
