# Generated by Django 4.2.4 on 2023-08-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_2_app', '0002_remove_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='reg_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
