# Generated by Django 4.2.4 on 2023-08-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hw_2_app', '0004_client_phone'),
    ]
    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='client',
            name='reg_date',
            field=models.DateField(),
        ),
    ]
